# Define the name of the workflow
name: test.yml

# Use the `push-trigger.yml` template
extends: bbhupati/GH-CICDTemplates/commons/push-trigger.yml@v1.0

# Define the event triggers for the workflow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    uses: bbhupati/GH-CICDTemplates/templates/build.yml@v1.0

  deploy:
    uses: bbhupati/GH-CICDTemplates/templates/deploy.yml@v1.0
