# Define the name of the workflow
name: test.yml

# Use the `push-trigger.yml` template
extends: .github/workflows/push-trigger.yml@v1.0

jobs:
  build:
    uses: bbhupati/GH-CICDTemplates/.github/workflows/build.yml@v1.0

  deploy:
    uses: bbhupati/GH-CICDTemplates/.github/workflows/deploy.yml@v1.0
