# Define the name of the workflow
name: test.yml

# Define the event triggers for the workflow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:    

jobs:
  build:
    uses: bbhupati/GH-CICDTemplates/.github/workflows/build.yml@master

  deploy:
    uses: bbhupati/GH-CICDTemplates/.github/workflows/deploy.yml@master
